// USAGE: 
// Always use the condition inDateRange for every trade, entry or exit


// --- Date Settings ---

var startDate = input.int(title='Start Date', defval=1, minval=1, maxval=31)
var startMonth = input.int(title='Start Month', defval=1, minval=1, maxval=12)
var startYear = input.int(title='Start Year', defval=2011, minval=1950, maxval=2050)

var endDate = input.int(title='End Date', defval=31, minval=1, maxval=31)
var endMonth = input.int(title='End Month', defval=12, minval=1, maxval=12)
var endYear = input.int(title='End Year', defval=2022, minval=1950, maxval=2050)

// Look if the close time of the current bar falls inside the date range
var inDateRange = time >= timestamp(syminfo.timezone, startYear, startMonth, startDate, 0, 0)
     and time < timestamp(syminfo.timezone, endYear, endMonth, endDate, 0, 0)


// ALL CODE


// Exit open market position when date range ends
if not inDateRange and barstate.isconfirmed
    strategy.close_all()
